### PR TITLE
Fix casts on addLabelsToIssue

### PR DESCRIPTION
**Pull request by dnfield**
Crashes at runtime right now - I think this kind of cast was valid at some point before Dart 2.0 but isn't anymore.

### CODE REVIEW

**Comment by kevmoo** [comment]
@dnfield – looks like you need to fix your formatting!

**Comment by dnfield** [comment]
Whups.  I leave my default at a higher value than 80.  Updated.  Thanks!

**Comment by kevmoo** [comment]
@dnfield – we don't have tests here. Have you verified this change?

**Comment by dnfield** [comment]
Yes - I'd be happy to add a test, but wasn't sure where the appropriate place would be.

**Comment by kevmoo** [comment]
> Yes - I'd be happy to add a test, but wasn't sure where the appropriate place would be.

Tests aren't run in CI anyway. Just wanted to check that YOU have verified this fixes things.

**Comment by tvolkert** [comment]
@Pacane @robbecker-wf

**Pull request merged**
