### PR TITLE
Add access to labels on Pull Requests

### PR DESCRIPTION
**Pull request by robbecker-wf**
This adds labels to pull requests. It's just a refinement of https://github.com/DirectMyFile/github.dart/pull/155 with some additional null handling

### CODE REVIEW

**Comment by robbecker-wf** [comment]
fyi @dnfield I'm adding to your PR and getting it over the finish line. Thanks for your contribution!

**Comment by robbecker-wf** [comment]
@tvolkert @Pacane any input/review on your end?

**Comment by robbecker-wf** [comment]
cool, thanks. merging.

**Comment by dnfield** [comment]
Thanks! 

I have my VSCode column widths set to 100 or 120 I believe - dartfmt uses 80 by defaul tand I keep forgetting.

**Pull request merged**
