### PR TITLE
Misc cleanup

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @Pacane

**Comment by Pacane** [comment]
Do you have the rights to merge? If not I'll merge/bump version/publish on sunday/Monday. 

Thanks!

**Comment by kevmoo** [comment]
@Pacane pushed one more commit. I don't have the ability to merge, though.

Thanks!

**Comment by Pacane** [comment]
I thought I had the pub rights to publish, but it seems only @kaendfinger has them.

**Comment by kaendfinger** [comment]
@Pacane I made you an uploader 👍 🥇 💯 😄

**Comment by Pacane** [comment]
@kevmoo I deployed your stuff on pub.

**Pull request merged**
