### PR TITLE
Fix RepositoriesService.listContributors

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
@Pacane – PTAL?

Could I be a contributor on this repo? So I could assign reviewers, approve PRs, etc?

**Comment by Pacane** [comment]
@kevmoo I added you, and yes I'll take a look. Thanks

**Comment by Pacane** [comment]
@kevmoo can this be merged?

**Comment by kevmoo** [comment]
@Pacane I will land this once travis is happy!

**Pull request merged**
